server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,evn,configprops,threaddump

spring:
  data:
    mongodb:
      database: deliveryrequest
      uri: mongodb://localhost:27017
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.05
  application:
    name: delivery-relay-service
