name: Delivery-Relay-Service

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit test
        run: ./gradlew --info delivery-relay-service:test

      - name: Run integration tests
        run: ./gradlew --info delivery-relay-service:integrationTest

      - name: Generate Jacoco Test Coverage
        run: ./gradlew --info :delivery-relay-service:generateJacocoTestCoverage

      - name: Comment test coverage on PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: 📝 테스트 커버리지 리포트
          paths: ${{ github.workspace }}/delivery-relay-service/build/jacoco/index.xml
          token: ${{ secrets.GITHUB_TOKEN }}