name: google-java-format

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 필요한 모든 히스토리를 가져오기 위해 fetch-depth를 0으로 설정합니다.
      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get current branch
        id: vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "Current branch: ${{ env.BRANCH_NAME }}"
          git status
          git branch -a
      - name: Checkout the branch
        run: git checkout ${{ env.BRANCH_NAME }}
      - name: List Directory Contents
        run: ls -al
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          commit-message: "Format: Google Java Format"
      - name: Push changes
        run: git push origin ${{ env.BRANCH_NAME }}